# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

name: test-coverage

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: |
          coverage <- covr::package_coverage()
          percentage <- round(covr::percent_coverage(coverage), 2)
          message("Coverage: ", percentage, "%")
          writeLines(as.character(percentage), "coverage.txt")
        shell: Rscript {0}

      - name: Create coverage badge
        run: |
          COVERAGE=$(cat coverage.txt)
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          curl -o coverage-badge.svg "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen?logo=R"

      - name: Upload coverage badge
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage-badge.svg

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
